# Fluid Configuration

# Navbar settings
navbar:
  blog_title: "FidelityAI"
  menu:
    - { key: "首页", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "服务项目", link: "/#services", icon: "iconfont icon-grid-fill" }
    - { key: "关于我们", link: "/about/", icon: "iconfont icon-user-fill" }
    - { key: "联系我们", link: "/contact/", icon: "iconfont icon-mail-fill" }

# Custom CSS / JS
custom_css: /css/custom.css
custom_js: /js/custom.js

# Home page banner settings
index:
  banner_img: 
  banner_img_height: 0
  banner_mask_alpha: 0
  slogan:
    enable: false
  subtitle:
    enable: false
  buttons: []


# Post settings
post:
  banner_img: https://images.unsplash.com/photo-1639322537228-f710d846310a?ixlib=rb-4.0.3&auto=format&fit=crop&w=1920&q=90
  banner_img_height: 50
  banner_mask_alpha: 0.6

# About page settings
about:
  banner_img:
  banner_img_height: 0
  banner_mask_alpha: 0
  layout: post

# Contact page settings
contact:
  banner_img:
  banner_img_height: 0
  banner_mask_alpha: 0
  layout: post

# Features page settings
features:
  banner_img: https://images.unsplash.com/photo-1518770660439-4636190af475?ixlib=rb-4.0.3&auto=format&fit=crop&w=1920&q=90
  banner_img_height: 50
  banner_mask_alpha: 0.6
  layout: post

# Global footer settings
footer:
  content: '<span>Copyright &copy; 2026 FidelityAI &nbsp;|&nbsp; 统一大模型接口网关</span>'
